config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :cities
  resources :countries
  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :categories
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to  :country
  has_many    :cities

  delegate :name , to: :country, prefix: true

  # Validations
  validates_presence_of :name, :acronym
  validates_uniqueness_of :name
  validates_length_of :name, maximum: 30
  validates_length_of :acronym, maximum: 2
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.includes(:country).order(:name)
  end

  # GET /states/1
  # GET /states/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.js { render :show }
    end
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :acronym, :country_id)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.haml
= simple_form_for(@state) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6
        = f.input :name
    .row
      .col-md-6
        = f.input :acronym
    .row
      .col-md-6
        = f.association :country

  .form-actions
    = f.button :submit , 'Gravar', class: 'btn btn-primary'

app/views/states/edit.html.haml
%h1 Editing state

= render 'form'

%p

= link_to 'Show', @state
\|
= link_to 'Back', states_path

app/views/states/index.html.haml
%h3 Listagem dos Estados

= link_to 'Novo Estado', new_state_path, class: 'btn btn-primary'

%p

  %table#states.table.table-bordered.table-striped{ cellspacing:"0" ,width: '100%' }
    %thead
      %tr
        %th
        %th Nome
        %th UF
        %th País
        %th
        %th

    %tbody
      - @states.each do |state|
        %tr 
          %td{ align: 'center' }= link_to 'Alterar', edit_state_path(state), class: 'btn btn-info btn-sm'
          %td
            = link_to state do 
              = simple_format(h(state.name))
          %td{ "data-href" => state_url(state) }
            = state.acronym
          %td{ "data-href" => state_url(state) }
            = state.country_name
          %td{ align: 'center '}= link_to 'Visualizar', state, class: 'btn btn-default btn-sm'
          %td{ align: 'center' }= link_to 'Excluir', state, :method => :delete, :data => { :confirm => 'Tem certeza?' }, class: 'btn btn-danger btn-sm'

%br

app/views/states/new.html.haml
%h1 New state

= render 'form'

= link_to 'Back', states_path

app/views/states/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @state.name
%p
  %b Acronym:
  = @state.acronym
%p
  %b Country:
  = @state.country_name

= link_to 'Alterar', edit_state_path(@state)
\|
= link_to 'Voltar', states_path