config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :cities
  resources :countries
  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :categories
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state

  delegate :name, :acronym, to: :state, prefix: true , allow_nil: true

  # Validations
  validates_length_of :name, maximum: 30
  validates_presence_of :name, :state_id
  validates_uniqueness_of :name, scope: [:name, :state_id]
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = initialize_grid(City.joins(:state), 
                              order: 'cities.name',
                              enable_export_to_csv: true,
                              csv_field_separator: ';', 
                              csv_file_name: 'cidades',
                              per_page: 10)

    export_grid_if_requested('grid' =>  'grid')
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.haml
= simple_form_for(@city) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6
        = f.input :name
    .row
      .col-md-6
        = f.association :state, collection: State.order('acronym ASC')

  .form-actions
    = f.button :submit, 'Gravar', class: 'btn-primary'

app/views/cities/_grid.html.haml
= define_grid(@cities, hide_submit_button: false, hide_reset_button: false, show_filters: :allways, allow_showing_all_records: false, upper_pagination_panel: true, html: { class: 'table table-striped table-hover table-condensed' }) do |g|

  - g.column in_csv: false, :html => {:style => 'text-align: center' } do |city|
    - link_to 'Alterar', edit_city_path(city), class: 'btn btn-info btn-xs'

  - g.column name: 'Cidade', attribute: 'name', detach_with_id: :city_filter

  - g.column name: 'Estado', attribute: 'name', assoc: :state, detach_with_id: :state_name_filter

  - g.column name: 'UF', attribute: 'acronym', assoc: :state, custom_filter: :auto

  - g.column in_csv: false, :html => {:style => 'text-align: center' } do |city|
    - link_to 'Visualizar', city, class: 'btn btn-default btn-xs'

  - g.column in_csv: false, :html => {:style => 'text-align: center' } do |city|
    - link_to 'Excluir', city, :method => :delete, :data => { :wonfirm => 'Tem certeza?'}, class: 'btn btn-danger btn-xs'

app/views/cities/edit.html.haml
%h1 Manutenção da Cidade

= render 'form'

%p

= link_to 'Visualizar', @city
|
= link_to 'Voltar', cities_path

app/views/cities/index.html.haml
.row-fluid
  .col-md-12
    %h3 
      = icon('list', class: 'text-primary')
      Listagem de Cidades

%p

= render 'grid'

.row
  .col-md-12
    .well
      .row
        .col-md-1
          %h5
            Cidade
        .col-md-4
          = grid_filter @cities, :city_filter
      .row
        .col-md-2
          .col-md-2.col-xs-12{ style: 'margin: 2px' }
          = link_to new_city_path, class: 'btn btn-primary col-xs-12' do
            = icon('plus')
            Nova Cidade
        .col-md-2.col-xs-6{ style: 'margin: 2px 0px' }
          %button.btn.btn-default.col-xs-12.wg-external-submit-button{ 'data-grid-name' => 'grid' }
            = icon('filter')
            Filtrar
        .col-md-2.col-xs-6{ style: 'margin: 2px 0px' }
          %button.btn.btn-info.col-xs-12.wg-external-reset-button{ 'data-grid-name' => 'grid' }
            = icon('refresh')
            Limpar
        .col-md-2.col-xs-12{ style: 'margin: 2px' }
          %button.btn.btn-success.col-xs-12.wg-external-csv-export-button{ 'data-grid-name' => 'grid' }
            Exportar CSV


= render_grid(@cities)

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @city.name
%p
  %b Estado:
  = @city.state_name

= link_to 'Alterar', edit_city_path(@city)
\|
= link_to 'Voltar', cities_path
\|
= link_to 'Novo', new_city_path