config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :cities
  resources :countries
  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :categories
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("backend_rknet.png", alt: "Home"), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.active
            %p.navbar-text 
              = current_user.email
              %span.sr-only
                (current)
          %li
            %p.navbar-text
              = link_to 'Sair', destroy_user_session_path, method: :delete, :class => 'navbar-link'
        - else
          = link_to 'Login', new_user_registration_path, :class => 'navbar-link'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Cadastros <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Paises', countries_url %></li>
      <li><%= link_to 'Estados', states_url %></li>
      <li><%= link_to 'Cidades', cities_url %></li>
      <li class="divider"></li>
      <li><%= link_to 'Categorias', categories_url %></li>
    </ul>
</li>

<li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Manutenção <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Manutenção 1', '#' %></li> 
      <li><%= link_to 'Manutenção 2', '#'%></li> 
    </ul>
</li>

<li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
     Relatórios<span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Relatório 1', '#' %></li> 
      <li><%= link_to 'Relatorio 2', '#' %></li> 
    </ul>
</li>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                Bem Vindo
            </a>
        </li>
        <li>
            <a href="#">Dashboard</a>
        </li>
        <li>
            <a href="#">Atalhos</a>
        </li>
        <li>
            <a href="#">Overview</a>
        </li>
        <li>
            <a href="#">Eventos</a>
        </li>
        <li>
            <a href="#">Sobre</a>
        </li>
        <li>
            <a href="#">Serviços</a>
        </li>
        <li>
            <a href="#">Contato</a>
        </li>
    </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : '.: RKNET - Composer :.'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Composer'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'

    %link{:rel => :stylesheet, :type => :"text/css", :href => "https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css"}

    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    = javascript_include_tag "https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      #wrapper.toggled
        = render 'layouts/sidebar'
        #page-content-wrapper
          .container-fluid
            .row
              .col-md-6
                %a{id: 'menu-toggle', class: 'btn btn-default btn-sm', :href => '#menu-toggle' , 'data-toggle' => 'offcanvas', 'role' => 'button' }
                  %span.icon-bar Expandir / Encolher
                  %span.icon-bar
                  %span.icon-bar
                  %span.icon-bar
              .col-md-6
            .row
              .col-lg-12
                = render 'layouts/messages'
            .row
              .col-lg-12
                = yield
<!-- Menu Toggle Script -->
:javascript
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });

app/views/layouts/login.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Composer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Composer'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'

    %link{:rel => :stylesheet, :type => :"text/css", :href => "https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css"}

    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    = javascript_include_tag "https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"
    = csrf_meta_tags
  %body
    %main{:role => "main"}
      #wrapper.toggled
        #page-content-wrapper
          .container-fluid
            .row
              .col-lg-12
                = render 'layouts/messages'
            .row
              .col-lg-12
                = yield
<!-- Menu Toggle Script -->
:javascript
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });